from instapy import InstaPy
username = input("Enter your instagram Username: ")
password = input("Enter your instagram password: ")
session = InstaPy(username,password)
session.login()
hastags = input("Enter the name of users, you want to like post ")
session.like_by_users([hastags], amount=10)
#session.set_dont_like(["naked", "murder", "nsfw"])
session.set_do_comment(True, percentage=100)
#session.set_comments(["Nice", "Amazing", "Super"])
#session.set_do_follow(enabled=True, percentage=100)
#session.set_user_interact(amount=1, randomize=True, percentage=100)
session.end() 
